Add random dog image widget example project
DataDog/apps pull request #69
Opened 2021-12-15 13:39 UTC by tdimnet

Turn the Random Dog Image hackathon project into an official example:

- Add set up scripts that create a dashboard and app.
- Detail the necessary environment variables

2021-12-16 20:57 UTC, joneshf-dd approved these changes
This looks great!

As mentioned in Slack, if you want the CI to be green before merging, you shoulc be able to pull the `master` branch (e.g. `git fetch && git merge origin/master && git push`). If that's not really something you want to do, you can merge the PR and it _should_ be fine. If not, we can always address it after the fact.

2021-12-16 23:34 UTC, duncanpharvey commented on examples/random-dog/dog-api/index.js
> +    console.log(url);
Delete console.log

2021-12-16 23:34 UTC, duncanpharvey commented on examples/random-dog/dog-api/index.js
> +    console.log(`imageUrl: ${imageUrl}`);
Delete console.log

2021-12-16 23:40 UTC, duncanpharvey commented on examples/random-dog/dog-image-widget/src/widget/index.tsx
> +                        label: 'Select a Dog Breed so see Random Images of',
Update label
```suggestion
                        label: 'Select a Dog Breed to get Random Images',
```

2021-12-17 00:57 UTC, duncanpharvey commented on examples/random-dog/dog-image-widget/src/widget/index.tsx
> +                }))
Add `All Breeds` option to widget (already supported by api)
```suggestion
                var options = breeds.map(breed => ({
                    label: breed['name'] as string,
                    value: breed['id'] as string
                }))
                options.unshift({ label: "All Breeds", value: "0" })
```

2021-12-17 01:39 UTC, duncanpharvey commented on examples/random-dog/dog-image-widget/src/widget/widget.css
> +}
Update css so image covers entire widget area

```suggestion
.main-wrapper {
    height: 100%;
    left: 0px;
    position: absolute;
    top: 0px;
    width: 100%;
}

.image-wrapper {
    height: 100%;
    width: 100%;
}

.new-dog-btn {
    background-color: rgba(100, 44, 165);
    border: none;
    color: white;
    left: 20px;
    position: absolute;
    top: 20px;
}

.dog-img {
    height: 100%;
    object-fit: cover;
    width: 100%;
}
```

2021-12-17 01:42 UTC, duncanpharvey commented on examples/random-dog/dog-image-widget/src/widget/widget.css
> +}
Update css so image covers entire widget area

```suggestion
.main-wrapper {
    height: 100%;
    left: 0px;
    position: absolute;
    top: 0px;
    width: 100%;
}

.image-wrapper {
    height: 100%;
    width: 100%;
}

.new-dog-btn {
    background-color: rgba(100, 44, 165);
    border: none;
    color: white;
    left: 20px;
    position: absolute;
    top: 20px;
}

.dog-img {
    height: 100%;
    object-fit: cover;
    width: 100%;
}
```

2021-12-17 01:49 UTC, duncanpharvey requested changes
I made a few suggestions for what can be updated in the code. What do you think?

Also two other minor improvements that could be made:
- The New Dog button stays gray after clicking on it. Why does it not change back to the original color after clicking on it?
- In the widget, the image looks better with `object-fit:cover` but in the widget editor the image looks better with `object-fit:contain`. Is there an easy method to add conditional logic to use one css rule in the widget and a different rule in the widget editor?

2021-12-17 14:07 UTC, duncanpharvey approved these changes

2021-12-17 14:08 UTC, duncanpharvey commented
Looks great! Thanks for making those updates

2021-12-17 16:35 UTC, merged